version: "3.8"

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: todo-app:dev
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - app/.venv/
