name: Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml up --build
  deploy:
    name: Deploy to Docker Hub and Heroku
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cameronmccormack
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build production app
        run: docker build --target prod --tag cameronmccormack/todo-app:${{ github.sha }} .

      - name: Tag image as latest production image
        run: docker tag cameronmccormack/todo-app:${{ github.sha }} cameronmccormack/todo-app:latest

      - name: Push image to Docker Hub 
        run: docker push cameronmccormack/todo-app:latest && docker push cameronmccormack/todo-app:${{ github.sha }}

      - name: Login to Heroku Container Registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 

      - name: Tag image for Heroku
        run: docker tag cameronmccormack/todo-app:${{ github.sha }} registry.heroku.com/cameronmccormack-todo-app/web

      - name: Push to Heroku Container Registry
        run: docker push registry.heroku.com/cameronmccormack-todo-app/web

      - name: Release image for display on Heroku Dyno
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a cameronmccormack-todo-app web
